---
site_name: Repository ORM
site_author: Lyz
site_url: https://lyz-code.github.io/repository-orm
nav:
  - Repository ORM: index.md
  - Repositories:
      - FakeRepository: fake_repository.md
      - TinyDBRepository: tinydb_repository.md
      - PypikaRepository: pypika_repository.md
  - Models: models.md
  - Testing: testing.md
  - API Reference:
      - Repository Implementations: reference_adapters.md
      - Models: reference_models.md
      - Exceptions: reference_exceptions.md
  - Contributing:
      - contributing.md
      - Create new repository: new_repo.md
  - Architecture Decision Records:
      - adr/adr.md
      - '001: Entity id_ definition': |
          adr/001-entity_id_definition.md
      - '002: String id_ support': |
          adr/002-support_string_ids.md
      - '003: Make entity_models optional arguments': |
          adr/003-make_entity_models_optional_arguments.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: true
            heading_level: 1
      watch:
        - src
  - autolinks
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - section-index

markdown_extensions:
  - abbr
  - def_list
  - admonition
  - markdown_include.include:
      base_path: docs
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  custom_dir: docs/theme
  # logo: 'images/logo.bmp'
  features:
    - navigation.instant
  palette:
    primary: blue grey
    accent: light blue

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css

repo_name: lyz-code/repository-orm
repo_url: https://github.com/lyz-code/repository-orm
